### ISSUE TITLE
Gradle execution error

### ISSUE THREAD

**Issue by michaelcli** [rpng/android-camera-calibration#4]
Hello!

I downloaded the repository, but I'm having trouble compiling the project, as Gradle throws an error: "The version of Gradle you are using (3.3) does not support the forTasks() method on BuildActionExecuter. Support for this is available in Gradle 3.5 and all later versions." In this case, I changed the gradle-wrapper.properties distributionUrl to 3.5, but then it said the project required version 3.3 of Gradle. 

Is there some way to solve or get around this Gradle version error? If not, is there an apk I can use to calibrate my camera? The app seems awesome, and I really want to try it. 

Thank you very much!

**Comment by goldbattle** [comment]
You might try moving the build system forward to the new version of gradle or look into how to force android studio to use the older version. Let me know if you have any success.

**Comment by michaelcli** [comment]
What should I modify to have the entire system work on Gradle 3.5? Also, is there already an apk of this out there that I could use to get the camera info for my phone? I was hoping to actually use this app to get the camera calibration info for my own phone. 

Thank you again, I really appreciate the help!

**Comment by goldbattle** [comment]
I would start with the build.gradle files, and then see what the compile errors are.
https://github.com/rpng/android-camera-calibration/blob/master/build.gradle
https://github.com/rpng/android-camera-calibration/blob/master/libraries/opencv_310/build.gradle

If I remember right, the issue is that it needs to use the jni and jnilibs with the android NDK, which was a pain to setup . I think it is now integrated, so it might be easier in the newer versions?
